image: gitpod/workspace-full

tasks:
  - name: "Sync GROQ secret & start stack"
    command: |
      # 1) Sincronizza il secret da GitHub in Gitpod
      gp secret sync-from-github GROQ_API_KEY || true

      # 2) Abort se manca il token
      if [ -z "$GROQ_API_KEY" ]; then
        echo "❌ GROQ_API_KEY non disponibile, abort."
        exit 1
      fi

      # 3) Esporta la variabile nella shell corrente
      export GROQ_API_KEY

      # 4) carica altre variabili dal file .env
      if [ -f .env ]; then
        export $(grep -v '^#' .env | xargs)
      fi

      # 5) Avvia l’intero stack
      docker-compose -f .devcontainer/docker-compose.yml up -d

ports:
  - port: 9093   # Kafka SSL
    onOpen: open-preview
  - port: 2181   # Zookeeper
    onOpen: ignore
  - port: 8080   # Airflow Webserver
    onOpen: open-preview
  - port: 8081   # NiFi
    onOpen: open-preview
  - port: 1883   # HiveMQ
    onOpen: ignore
