# .gitpod.yml
image: gitpod/workspace-full

# 1) Dichiariamo la variabile senza default: Gitpod mostrerà un prompt per inserirla
variables:
  GROQ_API_KEY:

tasks:
  - name: "Load GROQ_API_KEY & start stack"
    command: |
      # 1) La variabile GROQ_API_KEY è già disponibile grazie al prompt
      if [ -z "$GROQ_API_KEY" ]; then
        echo "❌ Devi inserire il token Groq in fase di avvio del workspace."
        exit 1
      fi

      # 2) Carica eventuali altre variabili da .env (se esiste)
      if [ -f .env ]; then
        export $(grep -v '^#' .env | xargs)
      fi

      # 3) Avvia lo stack in background
      docker-compose -f .devcontainer/docker-compose.yml up -d

ports:
  - port: 9093   # Kafka SSL
    onOpen: open-preview
  - port: 2181   # Zookeeper
    onOpen: ignore
  - port: 8080   # Airflow Webserver
    onOpen: open-preview
  - port: 8081   # NiFi
    onOpen: open-preview
  - port: 1883   # HiveMQ
    onOpen: ignore
