image: gitpod/workspace-full

tasks:
  - name: "Load GROQ_API_KEY & start stack"
    command: |
      # 1) Leggi il secret da Gitpod
      export GROQ_API_KEY="$(gp secret get GROQ_API_KEY)"

      # 2) Fail fast se manca
      if [ -z "$GROQ_API_KEY" ]; then
        echo "❌ GROQ_API_KEY mancante in Gitpod"
        exit 1
      fi

      # 3) Carica altre variabili da .env (se esiste)
      if [ -f .env ]; then
        export $(grep -v '^#' .env | xargs)
      fi

      # 4) Avvia il tuo stack Docker
      docker-compose -f .devcontainer/docker-compose.yml up -d

ports:
  - port: 9093   # Kafka SSL
    onOpen: open-preview
  - port: 2181   # Zookeeper
    onOpen: ignore
  - port: 8080   # Airflow Webserver
    onOpen: open-preview
  - port: 8081   # NiFi
    onOpen: open-preview
  - port: 1883   # HiveMQ
    onOpen: ignore
