apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse-server:8123
    jsonData:
      defaultDatabase: nearyou
      username: default
      port: 8123
      server: clickhouse-server
      tlsSkipVerify: true
      protocol: http
      host: clickhouse-server
    secureJsonData:
      password: pwe@123@l@
    editable: true
    isDefault: true