apiVersion: 1

datasources:
  - name: ClickHouse
    uid: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: nearyou
    user: default
    secureJsonData:
      password:
    isDefault: true

  - name: Postgres
    uid: Postgres
    type: postgres
    access: proxy
    url: postgres://nearuser:nearypass@postgres-postgis:5432/near_you_shops
    database: near_you_shops
    isDefault: false
