apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres-postgis:5432
    user: nearuser
    secureJsonData:
      password: nearypass
    jsonData:
      database: near_you_shops
      sslmode: disable
      postgresVersion: 1500
    editable: true