# uso l'ultima versione, in caso di problemi uso la 3.8
version: "3.9" 
services:

#qui eseguo VS code che non è altro cge il server CodeSpaces,
# installo python, posso fare docker-compose logs, lanciare script..
app:
  image: python:3.10-slim   
  
  #l'host è la VM che Github CodeSpaces crea, dentro il container in /workspace
  volumes:
    -..:/workspace:cached
    
  #per far rimanere il container sempre in esecuzione:
  command: sleep infinity
  privileged: true
  
  ##########################################################
  #Zookeeper per Kafla : in quanto coordina i broker, obbligatorio l'uso
  zookeeper:
    image: bitami/zookeeper:latest 
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      -"2181:2181"
  ###########################################################

  #Kafka: broker per messagistica/streaming, invia e ricevo su porta 9093 visto ssl (9092 per PLAINTEXT no critt)
  kafka:
    image: bitnami/kafka:latest
    volumes:
      - ./certs:/certs
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_LISTENERS=SSL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SSL:SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SSL
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=${KAFKA_KEYSTORE_PASS}
      - KAFKA_CFG_SSL_KEY_PASSWORD=${KAFKA_KEYSTORE_PASS}
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=${KAFKA_KEYSTORE_PASS}
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    ###########################################################

    #HIVEMQ:
    hivemq:
    image: hivemq/hivemq-ce:latest
    container_name:hivemq
    ports:
      -"1883:1883" # porta mqtt standard
      -"8080:8080" # per Ui (in caso di adozione)
    #############################################################
    
    #APACHE Nifi: dataflow, orchesto le pipeline,
    #prendo i mex da hiveMQ, trasformo pubblici du kafla o contrario
    nifi:
    image: apache/nifi:latest
    environment:
      - NIFI_WEB_HTTP_PORT=8081
    ports:
      - "8081:8081"
    
      
      
  
  
  
  
