version: "3.9"

services:
  app:
    image: python:3.10-slim
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    privileged: true

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      # Disabilita KRaft per utilizzare la modalità legacy con Zookeeper
      - KAFKA_ENABLE_KRAFT=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # Abilita il listener in modalità PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  hivemq:
    image: hivemq/hivemq-ce:latest
    ports:
      - "1883:1883"
      - "8080:8080"

  nifi:
    image: apache/nifi:latest
    environment:
      - NIFI_WEB_HTTP_PORT=8081
    ports:
      - "8081:8081"

volumes:
  kafka_data:
